// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module repos.
import type { Id, Meta } from "solarsql";

// The id of a row of repos.
export type ReposId = Id<"repos">;

export type Generated = {
  "insert or ignore into repos (path, host, owner, name)\n       select value ->> 'path', value ->> 'host', value ->> 'owner', value ->> 'name' from json_each(:rows)": {
    params: { rows: readonly { "path": ReposId; "host": string; "owner": string; "name": string }[] };
    row: {};
  };
  "select path, host, owner, name from repos order by path": {
    params: {};
    row: { path: ReposId; host: string; owner: string; name: string };
  };
  "select path from repos": {
    params: {};
    row: { path: ReposId };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into repos (path, host, owner, name)\n       select value ->> 'path', value ->> 'host', value ->> 'owner', value ->> 'name' from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "select path, host, owner, name from repos order by path": { params: [], encode: [], json: [], reads: ["repos"] },
  "select path from repos": { params: [], encode: [], json: [], reads: ["repos"] },
};
