// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module mise.
import type { Id, Meta } from "solarsql";

// The id of a row of tool_uses.
export type ToolUsesId = Id<"tool_uses">;
// The id of a row of tools.
export type ToolsId = Id<"tools">;

export type Generated = {
  "insert or ignore into tools (id, tool, version, install_path, installed, active)\n       select value ->> 'id', value ->> 'tool', value ->> 'version', value ->> 'install_path', value ->> 'installed', value ->> 'active'\n       from json_each(:rows)": {
    params: { rows: readonly { "id": ToolsId; "tool": string; "version": string; "install_path": string | null; "installed": number; "active": number }[] };
    row: {};
  };
  "insert or ignore into tool_uses (id, root, tool, version, source, installed)\n       select value ->> 'id', value ->> 'root', value ->> 'tool', value ->> 'version', value ->> 'source', value ->> 'installed'\n       from json_each(:rows)": {
    params: { rows: readonly { "id": ToolUsesId; "root": string; "tool": string; "version": string; "source": string | null; "installed": number }[] };
    row: {};
  };
  "\n    select tool, version, install_path, installed, active from tools order by tool, version": {
    params: {};
    row: { tool: string; version: string; install_path: string | null; installed: number; active: number };
  };
  "\n    select tool, version, source, installed from tool_uses where root = :root order by tool": {
    params: { root: string };
    row: { tool: string; version: string; source: string | null; installed: number };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into tools (id, tool, version, install_path, installed, active)\n       select value ->> 'id', value ->> 'tool', value ->> 'version', value ->> 'install_path', value ->> 'installed', value ->> 'active'\n       from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "insert or ignore into tool_uses (id, root, tool, version, source, installed)\n       select value ->> 'id', value ->> 'root', value ->> 'tool', value ->> 'version', value ->> 'source', value ->> 'installed'\n       from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "\n    select tool, version, install_path, installed, active from tools order by tool, version": { params: [], encode: [], json: [], reads: ["tools"] },
  "\n    select tool, version, source, installed from tool_uses where root = :root order by tool": { params: ["root"], encode: [], json: [], reads: ["tool_uses"] },
};
