// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module git.
import type { Id, Meta } from "solarsql";

// The id of a row of git_status.
export type GitStatusId = Id<"git_status">;
// The id of a row of worktrees.
export type WorktreesId = Id<"worktrees">;

export type Generated = {
  "insert or ignore into worktrees (path, repo_root, branch, head)\n       select value ->> 'path', value ->> 'repo_root', value ->> 'branch', value ->> 'head' from json_each(:rows)": {
    params: { rows: readonly { "path": WorktreesId; "repo_root": string; "branch": string | null; "head": string | null }[] };
    row: {};
  };
  "insert or ignore into git_status (root, branch, upstream, ahead, behind, dirty_count, untracked_count, observed_at)\n       select value ->> 'root', value ->> 'branch', value ->> 'upstream', value ->> 'ahead', value ->> 'behind',\n              value ->> 'dirty_count', value ->> 'untracked_count', value ->> 'observed_at' from json_each(:rows)": {
    params: { rows: readonly { "root": GitStatusId; "branch": string | null; "upstream": string | null; "ahead": number; "behind": number; "dirty_count": number; "untracked_count": number; "observed_at": number }[] };
    row: {};
  };
  "\n    select root, branch, dirty_count, untracked_count\n    from git_status where dirty_count > 0 order by dirty_count desc, root": {
    params: {};
    row: { root: GitStatusId; branch: string | null; dirty_count: number; untracked_count: number };
  };
  "\n    select root, branch, upstream, ahead, behind, dirty_count, untracked_count\n    from git_status where root = :root": {
    params: { root: GitStatusId };
    row: { root: GitStatusId; branch: string | null; upstream: string | null; ahead: number; behind: number; dirty_count: number; untracked_count: number };
  };
  "\n    select path, branch, head from worktrees where repo_root = :root order by path": {
    params: { root: string };
    row: { path: WorktreesId; branch: string | null; head: string | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into worktrees (path, repo_root, branch, head)\n       select value ->> 'path', value ->> 'repo_root', value ->> 'branch', value ->> 'head' from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "insert or ignore into git_status (root, branch, upstream, ahead, behind, dirty_count, untracked_count, observed_at)\n       select value ->> 'root', value ->> 'branch', value ->> 'upstream', value ->> 'ahead', value ->> 'behind',\n              value ->> 'dirty_count', value ->> 'untracked_count', value ->> 'observed_at' from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "\n    select root, branch, dirty_count, untracked_count\n    from git_status where dirty_count > 0 order by dirty_count desc, root": { params: [], encode: [], json: [], reads: ["git_status"] },
  "\n    select root, branch, upstream, ahead, behind, dirty_count, untracked_count\n    from git_status where root = :root": { params: ["root"], encode: [], json: [], reads: ["git_status"] },
  "\n    select path, branch, head from worktrees where repo_root = :root order by path": { params: ["root"], encode: [], json: [], reads: ["worktrees"] },
};
