// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module brew.
import type { Id, Meta } from "solarsql";

// The id of a row of brew_packages.
export type BrewPackagesId = Id<"brew_packages">;

export type Generated = {
  "insert or ignore into brew_packages (id, kind, name, version)\n       select value ->> 'id', value ->> 'kind', value ->> 'name', value ->> 'version'\n       from json_each(:rows)": {
    params: { rows: readonly { "id": BrewPackagesId; "kind": "formula" | "cask"; "name": string; "version": string }[] };
    row: {};
  };
  "select kind, name, version from brew_packages order by kind, name, version": {
    params: {};
    row: { kind: "formula" | "cask"; name: string; version: string };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into brew_packages (id, kind, name, version)\n       select value ->> 'id', value ->> 'kind', value ->> 'name', value ->> 'version'\n       from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "select kind, name, version from brew_packages order by kind, name, version": { params: [], encode: [], json: [], reads: ["brew_packages"] },
};
