-- Migration 0001_initial.sql. Generated by solarsql from the declared schema.
CREATE TABLE agents (
    pane_id text primary key not null,
    session_id text,
    name text,
    agent text not null,
    status text not null,
    focused integer not null default 0,
    cwd text not null,
    foreground_cwd text,
    root text,
    workspace_id text,
    tab_id text,
    title text
  ) strict;
CREATE TABLE git_status (
    root text primary key not null,
    branch text,
    upstream text,
    ahead integer not null default 0,
    behind integer not null default 0,
    dirty_count integer not null default 0,
    untracked_count integer not null default 0,
    observed_at integer not null
  ) strict;
CREATE TABLE providers (
    name text primary key not null,
    ok integer not null,
    observed_at integer not null,
    ms real not null,
    error text
  ) strict;
CREATE TABLE repos (
    path text primary key not null,
    host text not null,
    owner text not null,
    name text not null
  ) strict;
CREATE TABLE solarsql_assert (name text not null, ok integer not null) strict;
CREATE TABLE tool_uses (
    id text primary key not null,
    root text not null,
    tool text not null,
    version text not null,
    source text,
    installed integer not null
  ) strict;
CREATE TABLE tools (
    id text primary key not null,
    tool text not null,
    version text not null,
    install_path text,
    installed integer not null,
    active integer not null
  ) strict;
CREATE TABLE worktrees (
    path text primary key not null,
    repo_root text not null,
    branch text,
    head text
  ) strict;
CREATE TRIGGER solarsql_assert_check before insert on solarsql_assert
  when new.ok = 0
BEGIN
  select raise(abort, new.name);
END;
