// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module headsign.
import type { Id, Meta } from "solarsql";

// The id of a row of workflow_runs.
export type WorkflowRunsId = Id<"workflow_runs">;

export type Generated = {
  "insert or replace into workflow_runs (root, workflow, workflow_path, status, phase, total_iterations, attempts, last_failure, end_reason, stop_nudges, driver_agent, phase_entered_at)\n    select value ->> 'root', value ->> 'workflow', value ->> 'workflow_path', value ->> 'status', value ->> 'phase', value ->> 'total_iterations', value ->> 'attempts', value ->> 'last_failure', value ->> 'end_reason', value ->> 'stop_nudges', value ->> 'driver_agent', value ->> 'phase_entered_at'\n    from json_each(:rows)": {
    params: { rows: readonly { "root": WorkflowRunsId; "workflow": string; "workflow_path": string | null; "status": string; "phase": string | null; "total_iterations": number; "attempts": string | null; "last_failure": string | null; "end_reason": string | null; "stop_nudges": number; "driver_agent": string | null; "phase_entered_at": number | null }[] };
    row: {};
  };
  "select root, workflow, workflow_path, status, phase, total_iterations, attempts, last_failure, end_reason, stop_nudges, driver_agent, phase_entered_at\n    from workflow_runs order by status, root": {
    params: {};
    row: { root: WorkflowRunsId; workflow: string; workflow_path: string | null; status: string; phase: string | null; total_iterations: number; attempts: string | null; last_failure: string | null; end_reason: string | null; stop_nudges: number; driver_agent: string | null; phase_entered_at: number | null };
  };
  "select root, workflow, workflow_path, status, phase, total_iterations, attempts, last_failure, end_reason, stop_nudges, driver_agent, phase_entered_at\n    from workflow_runs where root = :root": {
    params: { root: WorkflowRunsId };
    row: { root: WorkflowRunsId; workflow: string; workflow_path: string | null; status: string; phase: string | null; total_iterations: number; attempts: string | null; last_failure: string | null; end_reason: string | null; stop_nudges: number; driver_agent: string | null; phase_entered_at: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or replace into workflow_runs (root, workflow, workflow_path, status, phase, total_iterations, attempts, last_failure, end_reason, stop_nudges, driver_agent, phase_entered_at)\n    select value ->> 'root', value ->> 'workflow', value ->> 'workflow_path', value ->> 'status', value ->> 'phase', value ->> 'total_iterations', value ->> 'attempts', value ->> 'last_failure', value ->> 'end_reason', value ->> 'stop_nudges', value ->> 'driver_agent', value ->> 'phase_entered_at'\n    from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "select root, workflow, workflow_path, status, phase, total_iterations, attempts, last_failure, end_reason, stop_nudges, driver_agent, phase_entered_at\n    from workflow_runs order by status, root": { params: [], encode: [], json: [], reads: ["workflow_runs"] },
  "select root, workflow, workflow_path, status, phase, total_iterations, attempts, last_failure, end_reason, stop_nudges, driver_agent, phase_entered_at\n    from workflow_runs where root = :root": { params: ["root"], encode: [], json: [], reads: ["workflow_runs"] },
};
