// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module report.
import type { Meta } from "solarsql";
import type { AgentsId } from "../herdr/solarsql.generated.ts";
import type { GitStatusId, WorktreesId } from "../git/solarsql.generated.ts";

export type Generated = {
  "\n    select a.pane_id, a.name, a.status, a.root, g.branch, g.dirty_count, g.untracked_count\n    from agents a join git_status g on g.root = a.root\n    where g.dirty_count > 0 and (:me is null or a.pane_id <> :me)\n    order by g.dirty_count desc, a.pane_id": {
    params: { me: AgentsId | null };
    row: { pane_id: AgentsId; name: string | null; status: string; root: string | null; branch: string | null; dirty_count: number; untracked_count: number };
  };
  "\n    select a.root, cast(count(*) as integer) as agents, cast(sum(a.status = 'working') as integer) as working,\n           cast(coalesce(g.dirty_count, 0) as integer) as dirty_count\n    from agents a left join git_status g on g.root = a.root\n    where a.root is not null\n    group by a.root having count(*) > 1 order by agents desc, a.root": {
    params: {};
    row: { root: string | null; agents: number; working: number | null; dirty_count: number };
  };
  "\n    select w.path, w.branch, w.repo_root\n    from worktrees w left join agents a on a.root = w.path\n    where a.pane_id is null and w.path <> w.repo_root order by w.path": {
    params: {};
    row: { path: WorktreesId; branch: string | null; repo_root: string };
  };
  "\n    select a.pane_id, a.name, a.status, a.cwd, a.root from agents a\n    left join repos r on r.path = a.root\n    where r.path is null and (:me is null or a.pane_id <> :me) order by a.pane_id": {
    params: { me: AgentsId | null };
    row: { pane_id: AgentsId; name: string | null; status: string; cwd: string; root: string | null };
  };
  "\n    select g.root, g.branch, g.dirty_count, g.untracked_count from git_status g\n    left join agents a on a.root = g.root\n    where a.pane_id is null and g.dirty_count > 0 order by g.dirty_count desc, g.root": {
    params: {};
    row: { root: GitStatusId; branch: string | null; dirty_count: number; untracked_count: number };
  };
  "\n    select g.root, g.branch, g.upstream, g.behind, g.ahead,\n           cast(count(a.pane_id) as integer) as agents\n    from git_status g join agents a on a.root = g.root\n    where g.behind > 0 and (:me is null or a.pane_id <> :me)\n    group by g.root order by g.behind desc, g.root": {
    params: { me: AgentsId | null };
    row: { root: GitStatusId; branch: string | null; upstream: string | null; behind: number; ahead: number; agents: number };
  };
};

export const generated: Meta<Generated> = {
  "\n    select a.pane_id, a.name, a.status, a.root, g.branch, g.dirty_count, g.untracked_count\n    from agents a join git_status g on g.root = a.root\n    where g.dirty_count > 0 and (:me is null or a.pane_id <> :me)\n    order by g.dirty_count desc, a.pane_id": { params: ["me"], encode: [], json: [] },
  "\n    select a.root, cast(count(*) as integer) as agents, cast(sum(a.status = 'working') as integer) as working,\n           cast(coalesce(g.dirty_count, 0) as integer) as dirty_count\n    from agents a left join git_status g on g.root = a.root\n    where a.root is not null\n    group by a.root having count(*) > 1 order by agents desc, a.root": { params: [], encode: [], json: [] },
  "\n    select w.path, w.branch, w.repo_root\n    from worktrees w left join agents a on a.root = w.path\n    where a.pane_id is null and w.path <> w.repo_root order by w.path": { params: [], encode: [], json: [] },
  "\n    select a.pane_id, a.name, a.status, a.cwd, a.root from agents a\n    left join repos r on r.path = a.root\n    where r.path is null and (:me is null or a.pane_id <> :me) order by a.pane_id": { params: ["me"], encode: [], json: [] },
  "\n    select g.root, g.branch, g.dirty_count, g.untracked_count from git_status g\n    left join agents a on a.root = g.root\n    where a.pane_id is null and g.dirty_count > 0 order by g.dirty_count desc, g.root": { params: [], encode: [], json: [] },
  "\n    select g.root, g.branch, g.upstream, g.behind, g.ahead,\n           cast(count(a.pane_id) as integer) as agents\n    from git_status g join agents a on a.root = g.root\n    where g.behind > 0 and (:me is null or a.pane_id <> :me)\n    group by g.root order by g.behind desc, g.root": { params: ["me"], encode: [], json: [] },
};
