// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module docker.
import type { Id, Meta } from "solarsql";

// The id of a row of container_ports.
export type ContainerPortsId = Id<"container_ports">;
// The id of a row of containers.
export type ContainersId = Id<"containers">;

export type Generated = {
  "insert or ignore into containers (id, name, image, state, health, created_at, started_at, finished_at, exit_code, oom_killed, restart_count, compose_project, compose_service)\n       select value ->> 'id', value ->> 'name', value ->> 'image', value ->> 'state', value ->> 'health',\n              value ->> 'created_at', value ->> 'started_at', value ->> 'finished_at', value ->> 'exit_code',\n              value ->> 'oom_killed', value ->> 'restart_count', value ->> 'compose_project', value ->> 'compose_service'\n       from json_each(:containers)": {
    params: { containers: readonly { "id": ContainersId; "name": string; "image": string; "state": string; "health": string | null; "created_at": number; "started_at": number | null; "finished_at": number | null; "exit_code": number; "oom_killed": number; "restart_count": number; "compose_project": string | null; "compose_service": string | null }[] };
    row: {};
  };
  "insert or ignore into container_roots (container_id, root)\n       select value ->> 'container_id', value ->> 'root' from json_each(:roots)": {
    params: { roots: readonly { "container_id": ContainersId; "root": string }[] };
    row: {};
  };
  "insert or ignore into container_ports (id, container_id, container_port, protocol, host_ip, host_port)\n       select value ->> 'id', value ->> 'container_id', value ->> 'container_port', value ->> 'protocol', value ->> 'host_ip', value ->> 'host_port'\n       from json_each(:ports)": {
    params: { ports: readonly { "id": ContainerPortsId; "container_id": ContainersId; "container_port": number; "protocol": string; "host_ip": string | null; "host_port": number | null }[] };
    row: {};
  };
  "\n    select id, name, image, state, health, created_at, started_at, finished_at, exit_code, oom_killed, restart_count, compose_project, compose_service\n    from containers\n    order by case when state = 'running' then 0 else 1 end, name": {
    params: {};
    row: { id: ContainersId; name: string; image: string; state: string; health: string | null; created_at: number; started_at: number | null; finished_at: number | null; exit_code: number; oom_killed: number; restart_count: number; compose_project: string | null; compose_service: string | null };
  };
  "\n    select c.id, c.name, c.image, c.state, c.health, c.created_at, c.started_at, c.finished_at, c.exit_code, c.oom_killed, c.restart_count, c.compose_project, c.compose_service\n    from containers c join container_roots r on r.container_id = c.id\n    where r.root = :root\n    order by case when c.state = 'running' then 0 else 1 end, c.name": {
    params: { root: string };
    row: { id: ContainersId; name: string; image: string; state: string; health: string | null; created_at: number; started_at: number | null; finished_at: number | null; exit_code: number; oom_killed: number; restart_count: number; compose_project: string | null; compose_service: string | null };
  };
  "\n    select c.name, c.state, p.container_id, p.container_port, p.protocol, p.host_ip, p.host_port\n    from container_ports p\n    join containers c on c.id = p.container_id\n    join container_roots r on r.container_id = c.id\n    where r.root = :root\n    order by p.host_port is null, p.host_port, case when c.state = 'running' then 0 else 1 end, p.container_port, p.protocol, c.name": {
    params: { root: string };
    row: { name: string; state: string; container_id: ContainersId; container_port: number; protocol: string; host_ip: string | null; host_port: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into containers (id, name, image, state, health, created_at, started_at, finished_at, exit_code, oom_killed, restart_count, compose_project, compose_service)\n       select value ->> 'id', value ->> 'name', value ->> 'image', value ->> 'state', value ->> 'health',\n              value ->> 'created_at', value ->> 'started_at', value ->> 'finished_at', value ->> 'exit_code',\n              value ->> 'oom_killed', value ->> 'restart_count', value ->> 'compose_project', value ->> 'compose_service'\n       from json_each(:containers)": { params: ["containers"], encode: ["containers"], json: [], reads: ["container_ports", "container_roots"] },
  "insert or ignore into container_roots (container_id, root)\n       select value ->> 'container_id', value ->> 'root' from json_each(:roots)": { params: ["roots"], encode: ["roots"], json: [], reads: ["containers"] },
  "insert or ignore into container_ports (id, container_id, container_port, protocol, host_ip, host_port)\n       select value ->> 'id', value ->> 'container_id', value ->> 'container_port', value ->> 'protocol', value ->> 'host_ip', value ->> 'host_port'\n       from json_each(:ports)": { params: ["ports"], encode: ["ports"], json: [], reads: ["containers"] },
  "\n    select id, name, image, state, health, created_at, started_at, finished_at, exit_code, oom_killed, restart_count, compose_project, compose_service\n    from containers\n    order by case when state = 'running' then 0 else 1 end, name": { params: [], encode: [], json: [], reads: ["containers"] },
  "\n    select c.id, c.name, c.image, c.state, c.health, c.created_at, c.started_at, c.finished_at, c.exit_code, c.oom_killed, c.restart_count, c.compose_project, c.compose_service\n    from containers c join container_roots r on r.container_id = c.id\n    where r.root = :root\n    order by case when c.state = 'running' then 0 else 1 end, c.name": { params: ["root"], encode: [], json: [], reads: ["container_roots", "containers"] },
  "\n    select c.name, c.state, p.container_id, p.container_port, p.protocol, p.host_ip, p.host_port\n    from container_ports p\n    join containers c on c.id = p.container_id\n    join container_roots r on r.container_id = c.id\n    where r.root = :root\n    order by p.host_port is null, p.host_port, case when c.state = 'running' then 0 else 1 end, p.container_port, p.protocol, c.name": { params: ["root"], encode: [], json: [], reads: ["container_ports", "container_roots", "containers"] },
};
