// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module sessions.
import type { Id, Meta } from "solarsql";

// The id of a row of sessions.
export type SessionsId = Id<"sessions">;

export type Generated = {
  "insert or ignore into sessions (session_id, agent, pid, cwd, root, name, kind, status, version, started_at, updated_at, last_turn_at, last_branch)\n       select value ->> 'session_id', value ->> 'agent', value ->> 'pid', value ->> 'cwd', value ->> 'root', value ->> 'name', value ->> 'kind', value ->> 'status', value ->> 'version', value ->> 'started_at', value ->> 'updated_at', value ->> 'last_turn_at', value ->> 'last_branch'\n       from json_each(:rows)": {
    params: { rows: readonly { "session_id": SessionsId; "agent": string; "pid": number | null; "cwd": string; "root": string | null; "name": string | null; "kind": string | null; "status": string | null; "version": string | null; "started_at": number | null; "updated_at": number | null; "last_turn_at": number | null; "last_branch": string | null }[] };
    row: {};
  };
  "\n    select session_id, agent, pid, cwd, root, name, kind, status, version, started_at, updated_at, last_turn_at, last_branch\n    from sessions order by agent, started_at": {
    params: {};
    row: { session_id: SessionsId; agent: string; pid: number | null; cwd: string; root: string | null; name: string | null; kind: string | null; status: string | null; version: string | null; started_at: number | null; updated_at: number | null; last_turn_at: number | null; last_branch: string | null };
  };
  "\n    select session_id, agent, pid, cwd, root, name, kind, status, version, started_at, updated_at, last_turn_at, last_branch,\n           cast((unixepoch('subsec') * 1000 - updated_at) / 60000 as integer) as idle_minutes\n    from sessions order by updated_at asc": {
    params: {};
    row: { session_id: SessionsId; agent: string; pid: number | null; cwd: string; root: string | null; name: string | null; kind: string | null; status: string | null; version: string | null; started_at: number | null; updated_at: number | null; last_turn_at: number | null; last_branch: string | null; idle_minutes: number | null };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into sessions (session_id, agent, pid, cwd, root, name, kind, status, version, started_at, updated_at, last_turn_at, last_branch)\n       select value ->> 'session_id', value ->> 'agent', value ->> 'pid', value ->> 'cwd', value ->> 'root', value ->> 'name', value ->> 'kind', value ->> 'status', value ->> 'version', value ->> 'started_at', value ->> 'updated_at', value ->> 'last_turn_at', value ->> 'last_branch'\n       from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "\n    select session_id, agent, pid, cwd, root, name, kind, status, version, started_at, updated_at, last_turn_at, last_branch\n    from sessions order by agent, started_at": { params: [], encode: [], json: [], reads: ["sessions"] },
  "\n    select session_id, agent, pid, cwd, root, name, kind, status, version, started_at, updated_at, last_turn_at, last_branch,\n           cast((unixepoch('subsec') * 1000 - updated_at) / 60000 as integer) as idle_minutes\n    from sessions order by updated_at asc": { params: [], encode: [], json: [], reads: ["sessions"] },
};
