// Generated by solarsql build. Do not edit.
// After a change to a statement, run `npx solarsql build`, and this file follows.
// Module github.
import type { Id, Meta } from "solarsql";

// The id of a row of pull_requests.
export type PullRequestsId = Id<"pull_requests">;
// The id of a row of review_requests.
export type ReviewRequestsId = Id<"review_requests">;

export type Generated = {
  "insert or ignore into pull_requests (id, repo, root, number, title, head_branch, head_repo, base_branch, author, is_draft, state, review_decision, checks, updated_at, url)\n       select value ->> 'id', value ->> 'repo', value ->> 'root', value ->> 'number', value ->> 'title', value ->> 'head_branch', value ->> 'head_repo', value ->> 'base_branch', value ->> 'author', value ->> 'is_draft', value ->> 'state', value ->> 'review_decision', value ->> 'checks', value ->> 'updated_at', value ->> 'url'\n       from json_each(:rows)": {
    params: { rows: readonly { "id": PullRequestsId; "repo": string; "root": string | null; "number": number; "title": string; "head_branch": string | null; "head_repo": string | null; "base_branch": string | null; "author": string | null; "is_draft": number; "state": string; "review_decision": string | null; "checks": string | null; "updated_at": number; "url": string }[] };
    row: {};
  };
  "insert or ignore into review_requests (id, repo, root, number, title, author, updated_at, url)\n       select value ->> 'id', value ->> 'repo', value ->> 'root', value ->> 'number', value ->> 'title', value ->> 'author', value ->> 'updated_at', value ->> 'url'\n       from json_each(:rows)": {
    params: { rows: readonly { "id": ReviewRequestsId; "repo": string; "root": string | null; "number": number; "title": string; "author": string | null; "updated_at": number; "url": string }[] };
    row: {};
  };
  "\n    select id, repo, root, number, title, head_branch, head_repo, base_branch, author, is_draft, state, review_decision, checks, updated_at, url\n    from pull_requests where root = :root order by number": {
    params: { root: string | null };
    row: { id: PullRequestsId; repo: string; root: string | null; number: number; title: string; head_branch: string | null; head_repo: string | null; base_branch: string | null; author: string | null; is_draft: number; state: string; review_decision: string | null; checks: string | null; updated_at: number; url: string };
  };
  "\n    select id, repo, root, number, title, author, updated_at, url\n    from review_requests order by updated_at desc": {
    params: {};
    row: { id: ReviewRequestsId; repo: string; root: string | null; number: number; title: string; author: string | null; updated_at: number; url: string };
  };
};

export const generated: Meta<Generated> = {
  "insert or ignore into pull_requests (id, repo, root, number, title, head_branch, head_repo, base_branch, author, is_draft, state, review_decision, checks, updated_at, url)\n       select value ->> 'id', value ->> 'repo', value ->> 'root', value ->> 'number', value ->> 'title', value ->> 'head_branch', value ->> 'head_repo', value ->> 'base_branch', value ->> 'author', value ->> 'is_draft', value ->> 'state', value ->> 'review_decision', value ->> 'checks', value ->> 'updated_at', value ->> 'url'\n       from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "insert or ignore into review_requests (id, repo, root, number, title, author, updated_at, url)\n       select value ->> 'id', value ->> 'repo', value ->> 'root', value ->> 'number', value ->> 'title', value ->> 'author', value ->> 'updated_at', value ->> 'url'\n       from json_each(:rows)": { params: ["rows"], encode: ["rows"], json: [], reads: [] },
  "\n    select id, repo, root, number, title, head_branch, head_repo, base_branch, author, is_draft, state, review_decision, checks, updated_at, url\n    from pull_requests where root = :root order by number": { params: ["root"], encode: [], json: [], reads: ["pull_requests"] },
  "\n    select id, repo, root, number, title, author, updated_at, url\n    from review_requests order by updated_at desc": { params: [], encode: [], json: [], reads: ["review_requests"] },
};
